<?php

namespace AppBundle\Repository;

/**
 * LibelleEtatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LibelleEtatRepository extends \Doctrine\ORM\EntityRepository
{
}
